name:                ghc-lexer
version:             0.1.0.0
github:              "carymrobbins/ghc-lexer"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2018 Cary Robbins"

extra-source-files:
- README.md

synopsis:            Short description of your package
category:            Language
description:         Please see the README on GitHub at <https://github.com/carymrobbins/ghc-lexer#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- directory
- haskeline
- ghc
- ghc-boot
- ghc-paths
- ghci
- mtl
- split
- template-haskell
- text

default-extensions:
- LambdaCase
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TemplateHaskell
- TypeApplications

ghc-options:
- -Wall
#- -Werror

library:
  source-dirs: src

executables:
  ghc-lexer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghc-lexer
